---
- name: Install ruby
  hosts: all
  become: true
  tasks:
  - name: Install ruby, bundler and etc.
    apt:
      name: "{{ item }}"
      state:  present
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
